spring:
  application:
    name: back
  profiles:
    active: dev
  config:
    import: classpath:application-secret.yml
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE
    com.back: DEBUG

springdoc:
  default-produces-media-type: application/json;charset=UTF-8

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

custom:
  jwt:
    secretKey: ijaoebj970n7unoijfkjy8978y9glkjslkej4coi8oijaoirj908oj9
  accessToken:
    expirationSeconds: 1200

app:
  frontend:
    base-url: http://localhost:3000